// Copyright 2025 Shreekara Rajendra
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apisshreekararajendradevv1alpha1 "github.com/shreekara-rajendra/KindToDigitalOcean/pkg/apis/shreekararajendra.dev/v1alpha1"
	versioned "github.com/shreekara-rajendra/KindToDigitalOcean/pkg/client/clientset/versioned"
	internalinterfaces "github.com/shreekara-rajendra/KindToDigitalOcean/pkg/client/informers/externalversions/internalinterfaces"
	shreekararajendradevv1alpha1 "github.com/shreekara-rajendra/KindToDigitalOcean/pkg/client/listers/shreekararajendra.dev/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DigitalClusterInformer provides access to a shared informer and lister for
// DigitalClusters.
type DigitalClusterInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() shreekararajendradevv1alpha1.DigitalClusterLister
}

type digitalClusterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDigitalClusterInformer constructs a new informer for DigitalCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDigitalClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDigitalClusterInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDigitalClusterInformer constructs a new informer for DigitalCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDigitalClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ShreekararajendraV1alpha1().DigitalClusters(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ShreekararajendraV1alpha1().DigitalClusters(namespace).Watch(context.TODO(), options)
			},
		},
		&apisshreekararajendradevv1alpha1.DigitalCluster{},
		resyncPeriod,
		indexers,
	)
}

func (f *digitalClusterInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDigitalClusterInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *digitalClusterInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisshreekararajendradevv1alpha1.DigitalCluster{}, f.defaultInformer)
}

func (f *digitalClusterInformer) Lister() shreekararajendradevv1alpha1.DigitalClusterLister {
	return shreekararajendradevv1alpha1.NewDigitalClusterLister(f.Informer().GetIndexer())
}
