// Copyright 2025 Shreekara Rajendra
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/shreekara-rajendra/KindToDigitalOcean/pkg/apis/shreekararajendra.dev/v1alpha1"
	shreekararajendradevv1alpha1 "github.com/shreekara-rajendra/KindToDigitalOcean/pkg/client/clientset/versioned/typed/shreekararajendra.dev/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeDigitalClusters implements DigitalClusterInterface
type fakeDigitalClusters struct {
	*gentype.FakeClientWithList[*v1alpha1.DigitalCluster, *v1alpha1.DigitalClusterList]
	Fake *FakeShreekararajendraV1alpha1
}

func newFakeDigitalClusters(fake *FakeShreekararajendraV1alpha1, namespace string) shreekararajendradevv1alpha1.DigitalClusterInterface {
	return &fakeDigitalClusters{
		gentype.NewFakeClientWithList[*v1alpha1.DigitalCluster, *v1alpha1.DigitalClusterList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("digitalclusters"),
			v1alpha1.SchemeGroupVersion.WithKind("DigitalCluster"),
			func() *v1alpha1.DigitalCluster { return &v1alpha1.DigitalCluster{} },
			func() *v1alpha1.DigitalClusterList { return &v1alpha1.DigitalClusterList{} },
			func(dst, src *v1alpha1.DigitalClusterList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.DigitalClusterList) []*v1alpha1.DigitalCluster {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.DigitalClusterList, items []*v1alpha1.DigitalCluster) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
